# Pusher
development:
  adapter_javascript_url: "http://js.pusher.com/2.0/pusher.min.js"
  app_id: <%= ENV['PUSHER_APP_ID'] %>
  api_key: <%= ENV['PUSHER_KEY'] %>
  auth_token: <%= ENV['PUSHER_SECRET'] %>
  adapter: "Pusher"
  async: true

# Disabled
# development:
#   adapter: false

test:
  adapter_javascript_url: "http://js.pusher.com/2.0/pusher.min.js"
  app_id: <%= ENV['PUSHER_APP_ID'] %>
  api_key: <%= ENV['PUSHER_KEY'] %>
  auth_token: <%= ENV['PUSHER_SECRET'] %>
  adapter: "Pusher"
  async: true

production:
  adapter_javascript_url: "http://js.pusher.com/2.0/pusher.min.js"
  app_id: <%= ENV['PUSHER_APP_ID'] %>
  api_key: <%= ENV['PUSHER_KEY'] %>
  auth_token: <%= ENV['PUSHER_SECRET'] %>
  adapter: "Pusher"
  async: true

# Faye
# development:
#   server: "http://localhost:9292/faye"
#   adapter_javascript_url: "http://localhost:9292/faye/faye.js"
#   auth_token: DEVELOPMENT_SECRET_TOKEN
#   adapter: "Faye"
#   async: true

# test:
#   server: "http://localhost:9292/faye"
#   adapter_javascript_url: "http://localhost:9292/faye/faye.js"
#   adapter: "Faye"
#   auth_token: "secret"
#   async: false
#
# production:
#   server: "http://example.com/faye"
#   adapter_javascript_url: "http://localhost:9292/faye/faye.js"
#   adapter: "Faye"
#   auth_token: "ddc12ef4f692e5d763a04abdb45b4e861ae22a231d4fa6711390415685ad0f6e"
#   async: true
